Lesson 06
4itosik/gocourse pull request #6
Opened 2020-11-06 11:47 UTC by 4itosik

2020-11-06 15:03 UTC, DmitriyVTitov requested changes
1. Неверная реакция на ошибку.
2. Данные после сканирования не обновляются, а просто сбрасываются в файл.

2020-11-06 15:03 UTC, DmitriyVTitov commented on lesson06/cmd/engine/main.go
> +func readFromFile(ind *index.Index) {
функция чтения из файла принимает почему-то не файл, а индекс.
а файл берётся из глобальной переменной.
это всё не очень хорошо. лучше передавать имя файла в функцию, а возвращаемое значение присваивать индексу.

2020-11-06 15:03 UTC, DmitriyVTitov commented on lesson06/cmd/engine/main.go
> +	readFromFile(ind)
функция делает разнонаправленные действия: читает файл и создаёт индекс

2020-11-06 15:03 UTC, DmitriyVTitov commented on lesson06/cmd/engine/main.go
> +	go crawlerSite(ind, url, 2)
crawler - это не глагол
scanSite - более-менее

2020-11-06 15:03 UTC, DmitriyVTitov commented on lesson06/cmd/engine/main.go
> +	}
ошибка и что? только сообщение?

https://github.com/hardcode-dev/go-core/blob/master/doc/%D0%A2%D0%B8%D0%BF%D0%BE%D0%B2%D1%8B%D0%B5%20%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B8.MD

2020-11-06 15:03 UTC, DmitriyVTitov commented on lesson06/cmd/engine/main.go
> +	}
нельзя продолжать при ошибке!

2020-11-06 15:03 UTC, DmitriyVTitov commented on lesson06/cmd/engine/main.go
> +	}
да, и почему индекс очищается при сканировании каждого сайта?

2020-11-06 15:03 UTC, DmitriyVTitov commented on lesson06/cmd/engine/main.go
> +	}
и этот побочный эффект надо убрать

2020-11-06 15:03 UTC, DmitriyVTitov commented on lesson06/cmd/engine/main.go
> +	go crawlerSite(ind, url, 2)
так а каким образом после того, как новые данные будут записаны в файл индекс обновится?
я тут не вижу.

2020-11-10 23:27 UTC, DmitriyVTitov approved these changes
OK, но есть недочёты.

2020-11-10 23:27 UTC, DmitriyVTitov commented on lesson06/cmd/engine/main.go
> +}
это что ещё за нововведения?

2020-11-10 23:27 UTC, DmitriyVTitov commented on lesson06/cmd/engine/main.go
> +}
зачем свой тип, если он вообще ничего не добавляет к встроенному типу ошибки?

2020-11-10 23:27 UTC, DmitriyVTitov commented on lesson06/cmd/engine/main.go
> +		}
if err, ok := err.(*fileError); !ok {
			log.Fatal(err)
		}

2020-11-10 23:27 UTC, DmitriyVTitov commented on lesson06/cmd/engine/main.go
> +		return nil, &fileError{"not found"}
можно просто объявить глобальную переменную (для ошибок это нормально), типа:
```
var ErrReadFile = errors.New(" .... ")
...
return nil, ErrReadFile
```

2020-11-10 23:27 UTC, DmitriyVTitov commented on lesson06/cmd/engine/main.go
> +	byteValue, err := ioutil.ReadFile(filename)
там не один байт, а целый массив

2020-11-10 23:27 UTC, DmitriyVTitov commented on lesson06/cmd/engine/main.go
> +	}
очень странная конструкция.
если ошибка возникла, то какая разница где? результат всё равно не валидный.
нужно в случае ошибки запускать сканирование синхронно.

2020-11-11 05:08 UTC, 4itosik commented on lesson06/cmd/engine/main.go
> +	}
тут история в том, ошибка `fileError` - значит что файла нет (например первый запуск) и у нас нет данных для индекса

2020-11-11 05:47 UTC, DmitriyVTitov commented on lesson06/cmd/engine/main.go
> +	}
а если файл есть, но повреждён, то сильно лучше стало?
типовая ошибка: работать с результатом в случае ошибки.

2020-11-13 11:07 UTC, merged