Lesson07
4itosik/gocourse pull request #7
Opened 2020-11-13 13:10 UTC by 4itosik

2020-11-20 03:01 UTC, DmitriyVTitov requested changes
Ошибка не проверяется!

2020-11-20 03:01 UTC, DmitriyVTitov commented on lesson07/cmd/gosearch/main.go
> +	go scanSite(gs)
а если `err != nil`?
всё равно запускаем `go scanSite(gs)`?

разве в случае ошибки не стоит выполнять синхронное сканирование?

2020-11-20 04:28 UTC, 4itosik commented on lesson07/cmd/gosearch/main.go
> +	go scanSite(gs)
согласен

2020-11-22 16:28 UTC, DmitriyVTitov approved these changes
Принято!

2020-11-22 16:28 UTC, DmitriyVTitov commented on lesson07/cmd/gosearch/main.go
> +}
Лучше сначала исключить плохие пути, а успешный путь не выделять отступами.
```
func (gs *gosearch) init() {
	fileData, err := gs.storage.ReadData()
	if err != nil {
		scanSite(gs)
                return
	}
	addToIndex(gs, fileData)
	go scanSite(gs)
}
```

2020-11-22 16:28 UTC, DmitriyVTitov commented on lesson07/cmd/gosearch/main.go
> +func scanSite(gs *gosearch) {
сервер в качестве аргумента выглядит странно.
лучше сделать такие функции методами.

2020-11-23 11:55 UTC, merged