Lesson 09
4itosik/gocourse pull request #9
Opened 2020-11-29 10:46 UTC by 4itosik

2020-11-30 14:39 UTC, DmitriyVTitov requested changes
Тесты должны быть в своих пакетах. То есть там же, где тестируемая функция.

2020-11-30 14:39 UTC, DmitriyVTitov commented on lesson09/cmd/searchbench/searchbench_test.go
> +	})
Эти бенчмарки (как и тесты) должны быть в своих пакетах, т.е. в `binary` и `bst`.
Не надо делать пакет, тем более `main` для тестов.

2020-11-30 14:39 UTC, DmitriyVTitov commented on lesson09/cmd/searchbench/searchbench_test.go
> +}
задача в задаче: видите путь, как сделать из этих двух почти одинаковых функций одну?

2020-12-01 06:59 UTC, 4itosik commented on lesson09/cmd/searchbench/searchbench_test.go
> +}
что то помучался и не получилось, подскажите как это сделать?

2020-12-01 10:56 UTC, DmitriyVTitov commented on lesson09/cmd/searchbench/searchbench_test.go
> +}
на практике, наверное, не стоит, но.
идея следующая: вынести тип элемента (чтобы оба пакета использовали одинаковый) и  объявить интерфейс с методом вставки, которому удовлетворяли бы и дерево и индекс. функция должна принимать интерфейс.
дальше вызывать функция для дерева и индекса по ситуации.

сам не пробовал, так что не ручаюсь, чисто мысленный эксперимент.

2020-12-03 14:46 UTC, DmitriyVTitov approved these changes
Почитайте про имена тестов и бенчмарков. Это очень важно.
И напишите мне где-нибудь, какой результат сравнения получился, что быстрее?

2020-12-03 14:46 UTC, DmitriyVTitov commented on lesson09/pkg/binary/binary_test.go
> +func BenchmarkBinary(b *testing.B) {
что за `Binary` если тестируется функция `Search`
имена бенчмарков должны быть такими же, как и имена тестов (только бенчмарки)

2020-12-03 14:46 UTC, DmitriyVTitov commented on lesson09/pkg/bst/bst_test.go
> +func BenchmarkBst(b *testing.B) {
и тут тоже имя неверное

2020-12-04 09:11 UTC, merged